### ISSUE TITLE
Client-Side Lua is not automatically initialized on singleplayer lobby created/destroyed

### ISSUE THREAD

**Issue by evilfactory** [evilfactory/Barotrauma-lua-attempt#40]
I dig in the code for 5 hours to find where the Lua initialization could be called, and i didn't have any luck, i need it to automatically start up if a singleplayer lobby is created and automatically destroy itself when the lobby is destroyed.

**Comment by zhu-rengong** [comment]
I tested it and it only works in single player mode, but I don't know what's the best way to destroy it

New Game → Next → Start → Initialization Lua
![TZAGQV0LL @I4Z`3G71J9GK](https://user-images.githubusercontent.com/73634685/153720374-d9489100-c7bf-4115-8cc4-dc93c474be2e.png)

Load Game → Load → Initialization Lua
![E01I_N8FX%SR2R2SKP 7%HD](https://user-images.githubusercontent.com/73634685/153720618-e271c037-5bcc-4f36-9e60-8176eb86d5fa.png)

Select Submarine Editor → Initialization Lua
![0Z4U27SE6SWAY3EMW}30 ~L](https://user-images.githubusercontent.com/73634685/153720643-8146811b-bbca-46d5-8faa-db488facb1fb.png)

Main Menu / Save and Quit → Destory Lua
![image](https://user-images.githubusercontent.com/73634685/153720708-be77a021-399e-4b59-93f7-c2cddee9149f.png)

**Comment by zhu-rengong** [comment]
My suggestion is here(Maybe):
![PIK3UFP~` 92JHFRJ%OH$KM](https://user-images.githubusercontent.com/73634685/153753482-3ad3cf0e-c0c8-4cb5-9fe1-af3fad9430b8.png)
![7IS{D9IA~OW BRMXXR_$)$A](https://user-images.githubusercontent.com/73634685/153753510-d11cd48b-b1f8-43d6-a2fd-d85330db2627.png)

But it is necessary to ensure that the initialization of lua runs before all hooks and destroys them after all hooks, otherwise some predefined hooks are useless, so the lua initialization above should be placed at the top.

And, I found a place that works great for client-side to destory lua, it happens in the following scenarios:
1. Exit the single player game by any means
2. Exit the multiplayer game by any means
3. Disconnect in any way
4. Type mainmenu|menu in the debug console
5. Exit in any way after testing in the submarine editor
![M2M}PM {)8SLS_%}{N)2_O](https://user-images.githubusercontent.com/73634685/153753691-02b98d46-1157-4a94-81ea-5034a8c2725c.png)

But this way will destory lua in netlobbyscreen hosted by client when select mode from multiplayer campaign to the other.
The above are all just suggestions, the code is giving me a headache.

**Comment by evilfactory** [comment]
yeah i don't think its usable, i don't want to Lua to be destroyed in the net lobby screen, i made a new commit [d3e0625](https://github.com/evilfactory/Barotrauma-lua-attempt/commit/d3e0625ef4f9b9ec47ed6d8ee4170fdd2b9720c9), roundStart and roundEnd hooks now work fine, and Lua is automatically initialized in singleplayer, but not in submarine editor.

**Comment by evilfactory** [comment]
Will look into trying to make this work in other screens, like subeditor and quickstart.

**Comment by evilfactory** [comment]
Fixed in unstable.
